// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pytuvhaoxavigwezkrsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5dHV2aGFveGF2aWd3ZXprcnNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3ODAyNDcsImV4cCI6MjA2OTM1NjI0N30.JTsgSKjmdWBYLY1k8OC8dMUw47SaA61YLzcHYjfKgY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});